/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/landing/banana_v1.glb --types
*/

import { Detailed, useGLTF } from '@react-three/drei';
import React from 'react';
import type * as THREE from 'three';
import { type GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
	nodes: {
		banana_high: THREE.Mesh;
		banana_mid: THREE.Mesh;
		banana_low: THREE.Mesh;
	};
	materials: {
		skin: THREE.MeshStandardMaterial;
	};
};

export const BananaModel = React.forwardRef<THREE.LOD, React.JSX.IntrinsicElements['lOD']>((props, ref) => {
	const { nodes, materials } = useGLTF('/landing/banana_v1.glb') as unknown as GLTFResult;
	return (
		<Detailed ref={ref} distances={[0, 65, 80]} {...props}>
			<mesh geometry={nodes.banana_high.geometry} material={materials.skin} material-emissive="#ff9f00" />
			<mesh geometry={nodes.banana_mid.geometry} material={materials.skin} material-emissive="#ff9f00" />
			<mesh geometry={nodes.banana_low.geometry} material={materials.skin} material-emissive="#ff9f00" />
		</Detailed>
	);
});

BananaModel.displayName = 'BananaModel';

useGLTF.preload('/landing/banana_v1.glb');
